#!/usr/bin/env bash
# run_matrix_mssql.sh — SQL Server feasibility + defense matrix on LocalDB (host sqlcmd).
# Usage: ./run_matrix_mssql.sh
# Produces results/RESULTS_mssql.md and results/_evidence_mssql.log
# Local, synthetic only. Low-priv attacker modelled via EXECUTE AS USER (LocalDB is Windows-auth).
set -uo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$DIR/../.." && pwd)"
RES="$ROOT/results/RESULTS_mssql.md"
EV="$ROOT/results/_evidence_mssql.log"
: > "$EV"

SQLCMD="/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/SQLCMD.EXE"
INST='(localdb)\MSSQLLocalDB'
run(){ "$SQLCMD" -S "$INST" -E -b -h -1 -W -i "$(cygpath -w "$DIR/$1")" 2>&1; }
build(){ echo "=== build victim ===" >>"$EV"; run 10_victim.sql >>"$EV" 2>&1; }
cell(){ echo -e "\n=== $1 ===" >>"$EV"; local out; out="$(run "$1")"; echo "$out" >>"$EV"; echo "$out"; }
tok(){ grep -oE "$1" <<<"$2" | head -1; }

echo "############ SQL Server (LocalDB) — feasibility matrix ############"
DBVER="$("$SQLCMD" -S "$INST" -E -h -1 -W -Q "SET NOCOUNT ON; SELECT CONCAT(CAST(SERVERPROPERTY('ProductVersion') AS varchar),' ',CAST(SERVERPROPERTY('Edition') AS varchar))" 2>>"$EV" | head -1)"

declare -a ROWS

# SH — shadow probe (N/A)
build; O="$(cell cell_sh.sql)"; SH="$(tok 'SH logged=[0-9]+' "$O")"
ROWS+=("| SH name-resolution shadow | app tries to shadow the capture path | **N/A** — no search_path; unqualified names in a dbo trigger resolve in dbo; built-in FOR JSON ($SH) | — | the PG 1A/1B class does not transfer |")

# 1C — replace trigger (ALTER on table) with verbatim restore
build; O="$(cell cell_1c_alter.sql)"
C="$(tok '1C blinded_logged=[0-9]+ ctl_logged=[0-9]+' "$O")"
HB="$(tok 'before hash=[0-9A-F]+' "$O")"; HA="$(tok 'after hash=[0-9A-F]+' "$O")"
REV="NO"; [ "${HB#*=}" = "${HA#*=}" ] && REV="YES (definition hash identical — verbatim restore, clean object diff)"
ROWS+=("| 1C replace trigger | ALTER on the table | **BLINDED** ($C) | $REV | ALTER permission on the table |")

# 1C-disable — the SQL-Server-specific primitive
build; O="$(cell cell_1c_disable.sql)"
D="$(tok '1Ddisable blinded_logged=[0-9]+ ctl_logged=[0-9]+ is_disabled_now=[0-9]+' "$O")"
ROWS+=("| 1C' DISABLE TRIGGER | ALTER on the table | **BLINDED** ($D) | **YES, zero residue** — definition unchanged, is_disabled returns to 0; only a canary/audit catches it | ALTER permission on the table |")

# 2G — session-gated dormant
build; O="$(cell cell_2g.sql)"; G="$(tok '2G gated_logged=[0-9]+ ctl_logged=[0-9]+' "$O")"
gv="did not behave as designed ($G)"; [[ "$G" == *"gated_logged=0 ctl_logged=1"* ]] && gv="DORMANT-BYPASS WORKS (gated skipped, ctl logged)"
ROWS+=("| 2 session dormant | ALTER on the table | **$gv** ($G) | at rest looks legit; **no extra audit grant needed** (ALTER keeps dbo ownership → chaining survives), easy like PostgreSQL | ALTER permission on the table |")

# 3P — attribution poisoning
build; O="$(cell cell_3p.sql)"; P="$(tok '3P ghost=[0-9]+ backdated=[0-9]+' "$O")"
pv="rejected"; [[ "$P" == *"ghost=1"* ]] && pv="POISONED (fabricated identity accepted)"
ROWS+=("| 3 attribution poison | INSERT on the audit table | **$pv** ($P) | **NO** — schema-identical to genuine rows; needs cross-layer correlation | INSERT on the audit table |")

# ---- defenses ----
build; O="$(cell def_priv.sql)"; DP="$(tok 'DPRIV logged=[0-9]+' "$O")"
DPRIV="app_user without ALTER on the table cannot DISABLE/replace the trigger (denied) → write still logged ($DP)"
build; O="$(cell def_ddlguard.sql)"
DGD="$(tok 'DDLGUARD disable_caught=[0-9]+' "$O")"; DGA="$(tok 'DDLGUARD alter_caught=[0-9]+' "$O")"
DDLG="DDL trigger catches ALTER ($DGA) but NOT DISABLE/ENABLE ($DGD) — DISABLE raises no DDL event (detection gap)"
build; O="$(cell def_hash.sql)"
HCI="$(tok 'HC intact=[A-Za-z0-9]+' "$O")"; HCT="$(tok 'HC tampered=[0-9]+' "$O")"
HC="$HCI; $HCT (non-NULL seq = tamper detected)"

# ---- write results ----
{
echo "# RESULTS — Self-Defeating Audits — SQL Server (LocalDB)"
echo
echo "_Local, synthetic lab. Generated by \`run_matrix_mssql.sh\`. Low-privilege attacker modelled"
echo "via \`EXECUTE AS USER='app_user'\` (LocalDB is Windows-auth only); permission checks are"
echo "enforced in that user's context._"
echo
echo "## Environment"
echo
echo "| Field | Value |"
echo "|---|---|"
echo "| Engine | SQL Server LocalDB |"
echo "| \`ProductVersion\` / Edition | ${DBVER} |"
echo
echo "> The SQL Server \"definer\" analogue is **ownership chaining** (trigger, business table, and"
echo "> audit table co-owned by \`dbo\`), so a low-privilege writer is audited without any direct"
echo "> grant on the audit table. SQL Server has **no \`search_path\`**; the PG 1A/1B class does not transfer."
echo
echo "## Feasibility matrix"
echo
echo "| Vector | Precondition | Result | Reversible / residue | True privilege needed |"
echo "|---|---|---|---|---|"
for r in "${ROWS[@]}"; do echo "$r"; done
echo
echo "## Defenses"
echo
echo "| Defense | Result |"
echo "|---|---|"
echo "| Remove ALTER on the table from app | ${DPRIV} |"
echo "| DDL-trigger guard (detection) | ${DDLG} |"
echo "| Hash-chained append-only sink | ${HC} |"
echo "| SQL Server Audit (engine-level) | recommended engine-level control (server/db audit to file/security log, outside the app principal's reach); not scripted on LocalDB |"
echo
echo "_Evidence: \`results/_evidence_mssql.log\`._"
} > "$RES"

echo "WROTE $RES"; echo "---- preview ----"; for r in "${ROWS[@]}"; do echo "$r"; done
echo "D-PRIV: $DPRIV"; echo "DDLGUARD: $DDLG"; echo "HC: $HC"
